### ISSUE TITLE
Rename crate?

### ISSUE THREAD

**Issue by revmischa** [projectM-visualizer/projectm-rs#5]
https://rust-lang.github.io/api-guidelines/naming.html

> Crate names should not use -rs or -rust as a suffix or prefix. Every crate is Rust! It serves no purpose to remind users of this constantly.

Should we rename it?

**Comment by blaquewithaq** [comment]
Yeah I'll rename projectm-rs to projectm. the -sys crate should remain the same.

**Comment by blaquewithaq** [comment]
There isn't a feature to rename crates, on crates.io. Its a requested feature tho lol. 

The only option is for me to re-upload the package as the new name and delete the old. Which would cause me to loose statistics...

**Comment by revmischa** [comment]
I think it's okay to delete the old one. don't think anything is using it yet except https://github.com/projectM-visualizer/frontend-sdl-rust

**Comment by blaquewithaq** [comment]
The crate has been renamed! You can now find it at: https://crates.io/crates/projectm

The old crate (https://crates.io/crates/projectm-rs) will be deleted 4/23.
